name: CI

on:
  push: {}
  #pull_request: {}

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7.7
      - name: Formatting checks
        shell: bash
        run: |
          ./scripts/formatting-checks.sh

  windows:
    needs: format
    runs-on: windows-latest

    env:
      BAZEL_VC: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC
      BAZEL_VS: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise

    steps:
      - uses: actions/checkout@v2
      - name: Build
        shell: cmd
        run: |
          call ./scripts/build.cmd

  ubuntu:
    needs: format
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build
        shell: bash
        run: |
          ./scripts/build.sh
