name: CI

on:
  push: {}

jobs:
  format:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8.10
      - name: Formatting checks
        shell: bash
        run: |
          ./scripts/formatting-checks.sh
          python3 ./scripts/file_naming.py

  windows:
    needs: format
    runs-on: windows-2019

    env:
      BAZEL_VC_FULL_VERSION: 14.29.30133
      BAZEL_VC: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC
      BAZEL_VS: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise

    steps:
      - uses: actions/checkout@v2
      - name: Build
        shell: cmd
        run: |
          call ./scripts/build.cmd

  gcc:
    needs: format
    runs-on: ubuntu-20.04
    env:
      CUDA_PATH: /usr/local/cuda-12.1
      CC_CONFIGURE_DEBUG: 1
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        shell: bash
        run: |
          ./scripts/install_deps.sh

      - name: Build
        shell: bash
        run: |
          bazelisk build --config=gcc --verbose_failures //...
          bazelisk test --config=gcc --verbose_failures //...

  clang:
    needs: format
    runs-on: ubuntu-20.04
    env:
      CUDA_PATH: /usr/local/cuda-12.1
      CC_CONFIGURE_DEBUG: 1
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        shell: bash
        run: |
          ./scripts/install_deps.sh

      - name: Build
        shell: bash
        run: |
          bazelisk build --config=clang --verbose_failures //...
          bazelisk test --config=clang --verbose_failures //...

      - name: Static code analysis
        shell: bash
        run: |
          bazelisk build --config=clang_tidy --keep_going //chroma-renderer/...
