name: CI

on:
  push: {}

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7.7
      - name: Formatting checks
        shell: bash
        run: |
          ./scripts/formatting-checks.sh
          python3.7 ./scripts/file_naming.py

  windows:
    needs: format
    runs-on: windows-latest

    env:
      BAZEL_VC: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC
      BAZEL_VS: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise

    steps:
      - uses: actions/checkout@v2
      - name: Build
        shell: cmd
        run: |
          call ./scripts/build.cmd

  ubuntu:
    needs: format
    runs-on: ubuntu-latest
    env:
      CUDA_PATH: /usr/local/cuda-10.2
      CC_CONFIGURE_DEBUG: 1
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        shell: bash
        run: |
          ./scripts/install_deps.sh

      - name: Build
        shell: bash
        run: |
          bazelisk build --config=linux --verbose_failures //...
          bazelisk test --config=linux --verbose_failures //...

      - name: Static code analysis
        shell: bash
        run: |
          bazelisk build --config=clang_tidy --keep_going //chroma-renderer/...
